/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "on-secondary-fixed-variant": "#004e5c",
        "secondary": "#00687a",
        "surface": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "outline": "#777587",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e3e4",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "on-surface-variant": "#464555",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "primary-container": "#4f46e5",
        "on-secondary-container": "#006172",
        "primary-fixed": "#e2dfff",
        "surface-container": "#edeeef",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#c3c0ff",
        "on-error": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-background": "#191c1d",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
        "primary": "#3525cd",
        "tertiary-container": "#a44100",
        "surface-tint": "#4d44e3",
        "tertiary": "#7e3000",
        "on-surface": "#191c1d",
        "secondary-fixed-dim": "#4cd7f6",
        "outline-variant": "#c7c4d8",
        "inverse-on-surface": "#f0f1f2",
        "on-primary": "#ffffff",
        "secondary-container": "#57dffe",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary-fixed": "#001f26",
        "inverse-surface": "#2e3132",
        "on-tertiary-container": "#ffd2be",
        "secondary-fixed": "#acedff",
        "on-primary-fixed-variant": "#3323cc",
        "on-tertiary-fixed": "#351000",
        "tertiary-fixed": "#ffdbcc"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "3xl": "1.5rem", "full": "9999px" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
